using STS2RitsuLib;
using STS2RitsuLib.Scaffolding.Content;
using MegaCrit.Sts2.Core.Models.CardPools;
using RabbitAndSteelNewMap.Scripts.Card;
using RabbitAndSteelNewMap.Scripts.Encounter;
using RabbitAndSteelNewMap.Scripts.Affliction;
using RabbitAndSteelNewMap.Scripts.Monster;
using RabbitAndSteelNewMap.Scripts.Power;
using RabbitAndSteelNewMap.Scripts.Enchantment;

namespace RabbitAndSteelNewMap.Scripts.Act;

public static class ContentRegistration
{
    public static void Register()
    {
        RitsuLibFramework.CreateContentPack(Entry.ModId)
            .Enchantment<BlueAttackGem>()
            .Enchantment<GreenAttackGem>()
            .Enchantment<RedAttackGem>()
            .Enchantment<PurpleAttackGem>()
            .Enchantment<YellowAttackGem>()
            .Enchantment<BlueSkillGem>()
            .Enchantment<GreenSkillGem>()
            .Enchantment<RedSkillGem>()
            .Enchantment<PurpleSkillGem>()
            .Enchantment<YellowSkillGem>()
            .Enchantment<BluePowerGem>()
            .Enchantment<GreenPowerGem>()
            .Enchantment<RedPowerGem>()
            .Enchantment<PurplePowerGem>()
            .Enchantment<YellowPowerGem>()
            .Enchantment<BlueBasicGem>()
            .Enchantment<GreenBasicGem>()
            .Enchantment<RedBasicGem>()
            .Enchantment<PurpleBasicGem>()
            .Enchantment<YellowBasicGem>()
            .Act<KingdomOutsideAct>()
            .Act<KingdomInsideAct>()
            .Act<UnderAct>()
            .Monster<Maxi>()
            .Monster<Rem>()
            .Monster<Bella>()
            .Monster<Sohko>()
            .Monster<Ita>()
            .Monster<Pine>()
            .Monster<Mav>()
            .Monster<Jay>()
            .Monster<Lette>()
            .Monster<Aus>()
            .Monster<Nimi>()
            .Monster<Orn>()
            .Monster<Blush>()
            .Monster<Avy>()
            .Monster<AvyBig>()
            .Monster<Matti>()
            .Monster<MattiBig>()
            .Monster<AusSmall>()
            .Monster<ItaSmall>()
            .Monster<MegSmall>()
            .Monster<NimiSmall>()
            .Monster<OrnSmall>()
            .Monster<PineSmall>()
            .Monster<VaroSmall>()
            .Monster<Meg>()
            .Monster<Varo>()
            .Monster<Mink>()
            .Monster<Ran>()
            .Monster<Xin>()
            .Monster<Tassha>()
            .Monster<TasshaPhantom>()
            .Monster<Merran>()
            .Monster<MerranBig>()
            .Power<AttackSideLeftPower>()
            .Power<AttackSideRightPower>()
            .Power<AttackSideFacingPower>()
            .Power<MerranAttackSideLeftPower>()
            .Power<MerranAttackSideRightPower>()
            .Affliction<RedColorMarkAffliction>()
            .Affliction<BlueColorMarkAffliction>()
            .Affliction<YellowColorMarkAffliction>()
            .Affliction<PurpleColorMarkAffliction>()
            .Affliction<GreenColorMarkAffliction>()
            .Power<TurbulencePower>()
            .Power<MaxiColorPower>()
            .Power<BlushColorPower>()
            .Power<RequiredColorPower>()
            .Power<PaintingPower>()
            .Power<PullAwayPower>()
            .Power<StillPower>()
            .Power<MovementPower>()
            .Power<ConstrainedPower>()
            .Power<HeavyPower>()
            .Power<StrainPower>()
            .Power<CallPower>()
            .Power<AvyRevivalPower>()
            .Power<MattiRevivalPower>()
            .Power<MerranRevivalPower>()
            .Power<MerranWindPower>()
            .Power<MerranAttentionPower>()
            .Power<MerranAttackCostPower>()
            .Power<MerranPhantomPower>()
            .Power<UnityPower>()
            .Power<FrogIdolPower>()
            .Power<HowlPower>()
            .Power<PhantomPower>()
            .Power<FearPower>()
            .Power<BalancePower>()
            .Card<ColorlessCardPool, Away>()
            .ActEncounter<KingdomOutsideAct, MaxiWeak>()
            .ActEncounter<KingdomOutsideAct, RemWeak>()
            .ActEncounter<KingdomOutsideAct, BellaWeak>()
            .ActEncounter<KingdomOutsideAct, SohkoWeak>()
            .ActEncounter<KingdomOutsideAct, ItaPineWeak>()
            .ActEncounter<KingdomOutsideAct, MavStrongEncounter>()
            .ActEncounter<KingdomOutsideAct, JayLetteWeak>()
            .ActEncounter<KingdomOutsideAct, AusNimiStrongEncounter>()
            .ActEncounter<KingdomOutsideAct, OrnStrongEncounter>()
            .ActEncounter<KingdomOutsideAct, BlushElite>()
            .ActEncounter<KingdomOutsideAct, AvyBoss>()
            .ActEncounter<KingdomOutsideAct, MattiBossEncounter>()
            .ActEncounter<KingdomOutsideAct, MegVaroEliteEncounter>()
            .ActEncounter<KingdomOutsideAct, MinkWeak>()
            .ActEncounter<KingdomOutsideAct, RanXinStrongEncounter>()
            .ActEncounter<KingdomOutsideAct, TasshaEliteEncounter>()
            .ActEncounter<KingdomOutsideAct, MerranBossEncounter>()
            .ActEnterUniformPool(0)
            .ActEnterUniformPoolCandidate<KingdomOutsideAct>(0, _ => true)
            .ActEnterUniformPool(1)
            .ActEnterUniformPoolCandidate<KingdomInsideAct>(1, _ => true)
            .ActEnterUniformPool(2)
            .ActEnterUniformPoolCandidate<UnderAct>(2, _ => true)
            .Apply();
    }
}
